version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directories:
      - "/packages/node"
      - "/samples/node"
      - "/site"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
      - "/packages/dotnet"
      - "/samples/dotnet"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories:
      - "/packages/go"
      - "/packages/go/bicep-rpc-client"
      - "/samples/go"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directories:
      - "/packages/python/bicep_testing"
      - "/packages/python/bicep_rpc_client"
      - "/samples/python"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns:
          - "*"